### PR TITLE
Create products schema and GET request for 25 top products

### PR DESCRIPTION
**Pull request by brunoportela**
- Create Products Schema: 

{
  Title: { type: String, required: true },
  Description: String,
  Category: String,
  ImageURL: String,
  Price: Number,
}

- Create GET request to TOP 25 products

### CODE REVIEW

**Review by J-DannyMartinez — APPROVED** [review]
👍🏼

**Review by MadinventorZero — APPROVED** [review]
Looks to be all in order

**Review by JIB3377 — APPROVED** [review]
No comments.

**Review by JohnL64 — APPROVED** [review]
yes! Yes!!

**Pull request merged**
